export { UAvatar as UAvatar1 } from './u-avatar-1.vue';
export { UAvatar as UAvatar2 } from './u-avatar-2.vue';
export { UAvatar as UAvatar3 } from './u-avatar-3.vue';
export { UAvatar as UAvatar4 } from './u-avatar-4.vue';
export { UAvatar as UAvatar5 } from './u-avatar-5.vue';
export { UAvatar as UAvatar6 } from './u-avatar-6.vue';
export { UAvatar as UAvatar7 } from './u-avatar-7.vue';
export { UAvatar as UAvatar8 } from './u-avatar-8.vue';
export { UAvatar as UAvatar9 } from './u-avatar-9.vue';
